Fix error messages and typo
ballerina-guides/ballerina-honeycomb pull request #12
Opened 2018-12-20 09:34 UTC by Shairam

## Purpose
> Improve error handling and fix typo issues.

2018-12-20 15:43 UTC, Anoukh commented on README.md
> +    // Resource configuration for getting marksa of a particular student.
```suggestion
    // Resource configuration for getting marks of a particular student.
```

2018-12-20 15:44 UTC, Anoukh commented on README.md
> +    // Get marks is a  resource used to get student's marks.
```suggestion
    // Resource used to get student's marks.
```

2018-12-20 15:45 UTC, Anoukh commented on README.md
> +// Function  to add students to the database.
```suggestion
// Function to add students to the database.
```

2018-12-20 15:46 UTC, Anoukh commented on README.md
> +// Function  to view all student's details to the database.
```suggestion
// Function to view all student's details
```

2018-12-20 15:46 UTC, Anoukh commented on guide/client_service/client_main.bal
> +        // Extracting data from JSON received.
```suggestion
        // Extracting data from received JSON.
```

2019-01-03 10:49 UTC, praneesha commented on README.md
> +// Port listener for the student service.
Listener of the student service port.

2019-01-03 10:49 UTC, praneesha commented on README.md
> +// Service configuration for student data service.
Service configuration for the student data service.

2019-01-03 10:50 UTC, praneesha commented on README.md
> +                log:printError("Error in converting JSON payload to student type", err = studentDetails);
Error in converting the JSON payload to the 'student' type.

2019-01-03 10:50 UTC, praneesha commented on README.md
> +            log:printError("Error obtaining the JSON payload", err = payloadJson);
Error in obtaining the JSON payload.

2019-01-03 10:51 UTC, praneesha commented on README.md
> +        // The below function adds tags that are to be passed as metrics in the traces. These tags are added to the default system span.
The below function adds tags to be passed as metrics in the traces. These tags are added to the default system span.

2019-01-03 10:51 UTC, praneesha commented on README.md
> +            log:printError("Error sending response", err = result);
Error in sending the response to the client.

2019-01-03 10:52 UTC, praneesha commented on README.md
> +    // Resource configuration for viewing all the student's details in the system.
Resource configuration for viewing details of all the students in the system.

2019-01-03 10:52 UTC, praneesha commented on README.md
> -            io:println("Select data from student table failed");
Error in selecting data from the student table.

2019-01-03 10:53 UTC, praneesha commented on README.md
> +           log:printError("Error in fetching students data from the database", err = returnValue);
Error in fetching details of all the students from the database.

2019-01-03 10:54 UTC, praneesha commented on README.md
> +            log:printError("Error in converting the data table from database to JSON", err = jsonConversionValue);
Error in converting the data from the tabular format to JSON.

2019-01-03 10:54 UTC, praneesha commented on README.md
> +            log:printError("Error in sending response", err = result);
Error in sending the response to the client.

2019-01-03 10:55 UTC, praneesha commented on README.md
> +        // The below function adds tags that are to be passed as metrics in the traces. These tags are added to the default system span.
The below function adds tags to be passed as metrics in the traces. These tags are added to the default system span.

2019-01-03 10:55 UTC, praneesha commented on README.md
> +    // Resource configuration for making a mock error to the system.
Resource configuration for generating a mock error in the system for observability purposes.

2019-01-03 10:56 UTC, praneesha commented on README.md
> +        // The below function adds tags that are to be passed as metrics in the traces. These tags are added to the default system span.
The below function adds tags to be passed as metrics in the traces. These tags are added to the default system span.

2019-01-03 10:56 UTC, praneesha commented on README.md
> +    // Resource configuration for deleting a students detail's from the system.
Resource configuration for deleting details of a student from the system.

2019-01-03 10:56 UTC, praneesha commented on README.md
> +        // The below function adds tags that are to be passed as metrics in the traces. These tags are added to the default system span.
The below function adds tags to be passed as metrics in the traces. These tags are added to the default system span.

2019-01-03 10:56 UTC, praneesha commented on README.md
> +    // Resource configuration for getting marksa of a particular student.
Resource configuration for retrieving the marks of a particular student.

2019-01-03 10:57 UTC, praneesha commented on README.md
> +            log:printError("Error in fetching marks from the marks system", err = requestReturn);
Error in fetching the marks from the system.

2019-01-03 10:57 UTC, praneesha commented on README.md
> +                log:printError("Error in extracting JSON from the response", err = msg);
Error in extracting the JSON payload from the response.

2019-01-03 10:57 UTC, praneesha commented on README.md
> +        //  The below function adds tags that are to be passed as metrics in the traces. These tags are added to the default system span.
The below function adds tags to be passed as metrics in the traces. These tags are added to the default system span.

2019-01-03 10:58 UTC, praneesha commented on README.md
> +                log:printError("Error in obtaining student ID from the database", err = returnValue2);
Error in obtaining the student ID from the database for the added student.

2019-01-03 10:59 UTC, praneesha commented on README.md
> +        log:printError("Error in adding the data to the database", err = returnValue);
Error in adding the data to the database.

2019-01-03 10:59 UTC, praneesha commented on README.md
> +        log:printError("Error in removing data from the database", err = returnValue);
Error in removing the data from the database.

2019-01-03 11:00 UTC, praneesha commented on README.md
> +        log:printError("Error obtaining student ID from the database", err = returnValue);
Error in obtaining a student ID from the database for the added student.

2019-01-03 11:00 UTC, praneesha commented on README.md
> +// Port listener for marks service.
Listener for the port of the marks service.

2019-01-03 11:00 UTC, praneesha commented on README.md
> +// Service configuration marks service.
Service configuration of the marks service.

2019-01-03 11:01 UTC, praneesha commented on README.md
> +    // Resource configuration for getting student's marks details from the system.
Resource configuration for retrieving marks of a student from the system.

2019-01-03 11:01 UTC, praneesha commented on README.md
> +    // Resource used to get student's marks.
Resource to retrieve the marks of a student.

2019-01-03 11:02 UTC, praneesha commented on README.md
> +        log:printError("Error in fetching data table from the database", err = returnValue);
Error in fetching the data table from the database.

2019-01-03 11:02 UTC, praneesha commented on README.md
> +        log:printError("Error in converting the data table to JSON", err = jsonConversionValue);
Error in converting the data from the tabular format to JSON.

2019-01-03 11:02 UTC, praneesha commented on README.md
> +// Host name for the student administration system server.
Hostname for the server hosting the student administration system.

2019-01-03 11:03 UTC, praneesha commented on README.md
> +            log:printError("Error in converting user selected option to int type", err = intOperation);
Error in converting the option selected by the user to an integer.

2019-01-03 11:04 UTC, praneesha commented on README.md
> +// Function to check if an input is integer
Function to check if an input is an integer.

2019-01-03 11:05 UTC, praneesha commented on README.md
> +        log:printError("Error in checking int type of " + input, err = isInt);
Error in checking if the 'input' variable is an integer.

2019-01-03 11:05 UTC, praneesha commented on README.md
> -        io:println("Adding students failed");
Error in adding student details.

2019-01-03 11:09 UTC, praneesha commented on README.md
> +        log:printError("Error in converting age and mobile number to int", err = ageAsInt);
Error in converting the age and the mobile number to integers.

2019-01-03 11:09 UTC, praneesha commented on README.md
> +        // Extracting data from received JSON.
Extracting data from the received JSON object.

2019-01-03 11:10 UTC, praneesha commented on README.md
> +            log:printError("Error in extracting JSON from response", err = jsonMsg);
Error in extracting the JSON payload from the received response.

2019-01-03 11:10 UTC, praneesha commented on README.md
> +        log:printError("Error in obtained response", err = resp);
Error in the obtained response.

2019-01-03 11:12 UTC, praneesha commented on README.md
> +// Function to view all student's details.
Function to view details of all the students.

2019-01-03 11:13 UTC, praneesha commented on README.md
> +            log:printError("Error in extracting JSON from response", err = jsonMsg);
Error in extracting the JSON payload from the received response.

2019-01-03 11:13 UTC, praneesha commented on README.md
> +        log:printError("Error in obtained response", err = resp);
Error in the obtained response.

2019-01-03 11:13 UTC, praneesha commented on README.md
> +// Function to delete a student's data from the system.
Function to delete the details of a student from the system

2019-01-03 11:14 UTC, praneesha commented on README.md
> +            log:printError("Error in extracting JSON from response", err = jsonMsg);
Error in extracting the JSON payload from the received response.

2019-01-03 11:14 UTC, praneesha commented on README.md
> +        log:printError("Error in obtained response", err = resp);
Error in the obtained response.

2019-01-03 11:14 UTC, praneesha commented on README.md
> +// Function to make a mock error in the system for observability purpose.
Function to generate a mock error in the system for observability purposes.

2019-01-03 11:15 UTC, praneesha commented on README.md
> +            log:printError("Error in fetching text from response", err = msg);
Error in fetching the text from the received response.

2019-01-03 11:15 UTC, praneesha commented on README.md
> +        log:printError("Error in obtained response", err = response);
Error in the obtained response.

2019-01-03 11:15 UTC, praneesha commented on README.md
> +// Function to fetch marks details of a student from the system.
Function to fetch the marks of a student from the system.

2019-01-03 11:16 UTC, praneesha commented on README.md
> +    // Get student ID.
Get the student ID of a particular student.

2019-01-03 11:16 UTC, praneesha commented on README.md
> +            log:printError("Error in extracting JSON from response", err = jsonMsg);
Error in extracting the JSON payload from the response.

2019-01-03 11:16 UTC, praneesha commented on README.md
> +        log:printError("Error in obtained response ", err = response);
Error in the obtained response.

2019-01-03 11:27 UTC, praneesha requested changes
Added a few suggestions.

2019-01-04 04:32 UTC, praneesha approved these changes

2019-01-04 04:32 UTC, merged